import { createSignal, Show, onMount } from 'solid-js'
import { Renderer } from '../renderer/Renderer'
import type { UIComponent } from '../renderer/types'

const DEFAULT_PROMPT = `Create a system health monitoring dashboard for an AI-powered UI platform.
The platform uses containers (industry templates) built via LLM chat conversations.
Entity types are first generated by the LLM into a manifest (staging), then materialized into the database.
Show the full pipeline: chat messages → manifest types → materialized types → live entities.`

/**
 * Flat dashboard descriptor — what the LLM returns.
 * Simple structure, no nested UI components.
 */
interface DashboardDescriptor {
  title: string
  status: { label: string; healthy: boolean }
  stats: Array<{ label: string; value: string }>
  recommendations: Array<{ priority: 'high' | 'medium' | 'low'; message: string }>
  sections: Array<{
    label: string
    type: 'table' | 'list' | 'alert'
    columns?: string[]
    rows?: string[][]
    items?: string[]
    message?: string
    variant?: string
  }>
}

/** Convert flat descriptor → Renderer UIComponent spec */
function descriptorToSpec(d: DashboardDescriptor): UIComponent {
  const children: UIComponent[] = [
    // Header
    {
      type: 'Row', props: { gap: '4', align: 'center' }, children: [
        { type: 'Heading', props: { level: 1, content: d.title } },
        { type: 'Badge', props: { label: d.status.label, variant: d.status.healthy ? 'success' : 'warning' } },
      ],
    },
    // Stat cards
    {
      type: 'Row', props: { gap: '4' }, children: d.stats.map(s => ({
        type: 'Card', props: { title: s.label }, children: [
          { type: 'Heading', props: { level: 2, content: s.value } },
        ],
      })),
    },
  ]

  // Recommendations
  const recs = d.recommendations ?? []
  if (recs.length > 0) {
    const variantMap = { high: 'warning', medium: 'info', low: 'default' } as Record<string, string>
    children.push({
      type: 'Card', props: { title: 'Recommended Next Steps' }, children: [
        {
          type: 'Stack', props: { gap: '2' }, children: recs.map(r => ({
            type: 'Alert', props: {
              title: `[${r.priority.toUpperCase()}] ${r.message}`,
              variant: variantMap[r.priority] ?? 'default',
            },
          })),
        },
      ],
    })
  }

  // Sections as tabs
  children.push({
    type: 'Tabs',
    props: {
      tabs: d.sections.map(s => ({
        label: s.label,
        value: s.label.toLowerCase().replace(/\s+/g, '_'),
        children: [sectionToNode(s)],
      })),
    },
  })

  return { type: 'Stack', props: { gap: '6' }, children }
}

function sectionToNode(s: DashboardDescriptor['sections'][number]): UIComponent {
  if (s.type === 'table' && s.columns && s.rows) {
    return { type: 'Table', props: { columns: s.columns, rows: s.rows } }
  }
  if (s.type === 'list' && s.items) {
    return { type: 'List', props: { items: s.items, variant: 'ordered' } }
  }
  // alert or fallback
  return { type: 'Alert', props: { title: s.message ?? s.label, variant: s.variant ?? 'default' } }
}

const SCHEMA_TEMPLATE = `{
  "title": "string — dashboard title",
  "status": { "label": "string", "healthy": true/false },
  "stats": [
    { "label": "Containers", "value": "1" },
    { "label": "Chat Messages", "value": "2" }
  ],
  "recommendations": [
    { "priority": "high", "message": "26 entity types identified in chat but 0 saved to manifest. Open the container and click Save All to persist them." },
    { "priority": "medium", "message": "No schemas generated yet. After saving to manifest, run Generate Schemas to materialize types into the database." }
  ],
  "sections": [
    {
      "label": "Containers",
      "type": "table",
      "columns": ["Name", "Status", "Messages"],
      "rows": [["Financial Audit", "draft", "2"]]
    },
    {
      "label": "Migrations",
      "type": "list",
      "items": ["001_initial.sql", "002_containers.sql"]
    },
    {
      "label": "Orphans",
      "type": "alert",
      "message": "No orphans detected",
      "variant": "success"
    }
  ]
}`

export default function HealthDynamicIsland() {
  const [spec, setSpec] = createSignal<UIComponent | null>(null)
  const [descriptor, setDescriptor] = createSignal<DashboardDescriptor | null>(null)
  const [loading, setLoading] = createSignal(false)
  const [error, setError] = createSignal<string | null>(null)
  const [provider, setProvider] = createSignal('ollama')
  const [customPrompt, setCustomPrompt] = createSignal('')
  const [rawJson, setRawJson] = createSignal('')
  const [showJson, setShowJson] = createSignal(false)

  onMount(() => { generate() })

  async function generate() {
    setLoading(true)
    setError(null)
    setSpec(null)
    setRawJson('')

    try {
      // 1. Fetch health data
      const healthRes = await fetch('/api/v1/admin/health')
      if (!healthRes.ok) throw new Error(await healthRes.text())
      const data = await healthRes.json()

      // 2. Build prompt — ask LLM for flat descriptor
      const basePrompt = customPrompt() || DEFAULT_PROMPT
      const fullPrompt = `${basePrompt}

Here is the live system health data:

${JSON.stringify(data, null, 2)}

Return a JSON object matching this EXACT schema (fill in real values from the data above):

${SCHEMA_TEMPLATE}

Rules:
- "stats": one entry per pipeline stage: Containers, Chat Messages, Chat Identified Types, Manifest Types (saved), Materialized Types (DB), Live Entities, App Users. Use actual counts as strings.
- "recommendations": Analyze the pipeline state and give actionable, specific next steps. Priority: "high" for blockers, "medium" for improvements, "low" for nice-to-haves. Factor in the NUMBER of identified types to give contextual advice:
  - 0 messages: tell them to start chatting to describe their domain
  - Messages but 0 chat_identified_types: tell them to ask the LLM to define entity types
  - chat_identified_types > 0 but manifest_type_count = 0: types need saving. If 20+ types, warn to review for redundancy first. If < 5 types, suggest chatting more to flesh out the model. Otherwise say it's a solid foundation.
  - manifest_type_count > 0 but materialized_type_count = 0: run "Generate Schemas" to create type packages
  - materialized_type_count > 0 but entity_count = 0: launch the app and start entering data
  - If chat_identified_types > manifest_type_count: some types were lost, re-run "Save All"
  - If containers are in "draft" status with 10+ types: review and lock
  - If there are orphans: investigate and clean up
  - If no app_users but materialized types exist: invite users
  - Reference specific container names and actual counts in recommendations
- "sections": one per logical group. type must be "table", "list", or "alert".
- Containers section: columns=[Name, Slug, Status, Messages, Chat Identified, Manifest, Materialized, Entities, Users], one row per container.
- All Tables section: columns=[Table, Row Count], one row per entry in data.tables.
- Recent Activity: if empty use type "alert" with message "No recent activity".
- Orphans: if empty use type "alert" message "No orphans detected" variant "success". Otherwise type "table".
- Migrations: type "list" with migration name strings.
- Return ONLY the JSON object. No markdown, no explanation.`

      // 3. Call raw descriptor endpoint
      const genRes = await fetch('/api/v1/admin/generate-descriptor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: fullPrompt, provider: provider() }),
      })

      const result = await genRes.json()
      if (result.error) throw new Error(result.error + (result.raw ? '\n' + result.raw : ''))

      const desc = result.descriptor as DashboardDescriptor
      setDescriptor(desc)
      setRawJson(JSON.stringify(desc, null, 2))

      // 4. Map flat descriptor → UI spec
      const uiSpec = descriptorToSpec(desc)
      setSpec(uiSpec)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div class="dark min-h-screen" style={{ "background-color": "var(--ui-bg)", "font-family": "var(--ui-font)" }}>
      {/* Header bar */}
      <header class="flex items-center justify-between px-6 py-3 border-b"
        style={{ "background-color": "var(--ui-card-bg)", "border-color": "var(--ui-border)" }}
      >
        <div class="flex items-center gap-4">
          <a href="/dashboard"><img src="/icon.png" alt="LevelNine" style={{ height: "28px" }} /></a>
          <a href="/dashboard" class="text-sm px-3 py-1 rounded-lg border hover:opacity-80"
            style={{ "border-color": "var(--ui-border)", color: "var(--ui-text-muted)" }}>Dashboard</a>
          <a href="/containers" class="text-sm px-3 py-1 rounded-lg border hover:opacity-80"
            style={{ "border-color": "var(--ui-border)", color: "var(--ui-text-muted)" }}>Containers</a>
        </div>
        <div class="flex items-center gap-3">
          <a href="/dashboard" class="text-sm px-3 py-1 rounded-lg border hover:opacity-80"
            style={{ "border-color": "var(--ui-border)", color: "var(--ui-text-muted)" }}>Dashboard</a>
          <a href="/health-dynamic" class="text-sm font-medium px-3 py-1 rounded-lg"
            style={{ "background-color": "var(--ui-primary-light)", color: "var(--ui-primary)" }}>Dynamic</a>
        </div>
      </header>

      <div class="max-w-6xl mx-auto px-6 py-8">
        <h1 class="text-2xl font-bold mb-1" style={{ color: "var(--ui-text)" }}>
          Dynamic Health Dashboard
        </h1>
        <p class="text-sm mb-6" style={{ color: "var(--ui-text-muted)" }}>
          LLM generates a dashboard descriptor from live health data. Code maps it to UI components.
        </p>

        {/* Controls */}
        <div class="flex gap-3 mb-6 flex-wrap items-end">
          <div class="flex flex-col gap-1">
            <label class="text-xs" style={{ color: "var(--ui-text-muted)" }}>Provider</label>
            <select
              value={provider()}
              onChange={(e) => setProvider(e.currentTarget.value)}
              class="rounded-lg px-3 py-2 text-sm min-w-[140px]"
              style={{ "background-color": "var(--ui-bg-muted)", color: "var(--ui-text)", border: "1px solid var(--ui-border)" }}
            >
              <option value="ollama">Ollama</option>
              <option value="gemini">Gemini</option>
              <option value="openai">OpenAI</option>
              <option value="xai">xAI</option>
            </select>
          </div>

          <div class="flex flex-col gap-1 flex-1">
            <label class="text-xs" style={{ color: "var(--ui-text-muted)" }}>Prompt (edit to customize)</label>
            <textarea
              value={customPrompt()}
              onInput={(e) => setCustomPrompt(e.currentTarget.value)}
              placeholder={DEFAULT_PROMPT}
              rows={3}
              class="rounded-lg px-3 py-2 text-sm resize-y"
              style={{ "background-color": "var(--ui-bg-muted)", color: "var(--ui-text)", border: "1px solid var(--ui-border)", "font-family": "inherit" }}
            />
          </div>

          <button
            onClick={generate}
            disabled={loading()}
            class="px-5 py-2 text-sm font-semibold rounded-lg cursor-pointer whitespace-nowrap transition-opacity hover:opacity-80"
            style={{
              "background-color": loading() ? "var(--ui-primary-hover)" : "var(--ui-primary)",
              color: "var(--ui-bg)",
              opacity: loading() ? "0.7" : "1",
              cursor: loading() ? "wait" : "pointer",
            }}
          >
            {loading() ? 'Generating...' : 'Generate UI'}
          </button>
        </div>

        <Show when={loading()}>
          <div class="flex items-center justify-center gap-3 py-10 rounded-xl border"
            style={{ "background-color": "var(--ui-primary-subtle)", "border-color": "var(--ui-primary-light)" }}
          >
            <div class="w-5 h-5 border-2 rounded-full animate-spin" style={{ "border-color": "var(--ui-primary)", "border-top-color": "transparent" }} />
            <span class="text-sm" style={{ color: "var(--ui-text-muted)" }}>LLM is generating your dashboard...</span>
          </div>
        </Show>

        <Show when={error()}>
          <div class="rounded-lg border px-4 py-3 text-sm mb-4"
            style={{ color: "var(--ui-error)", "background-color": "var(--ui-error-bg)", "border-color": "var(--ui-error-border)" }}
          >
            {error()}
          </div>
        </Show>

        <Show when={spec()}>
          <div class="flex justify-end gap-2 mb-3">
            <button
              onClick={() => setShowJson(!showJson())}
              class="px-3 py-1.5 text-xs rounded-lg cursor-pointer border transition-opacity hover:opacity-80"
              style={{ color: "var(--ui-text-muted)", "border-color": "var(--ui-border)", "background-color": "transparent" }}
            >
              {showJson() ? 'Hide JSON' : 'Show JSON'}
            </button>
            <button
              onClick={generate}
              class="px-3 py-1.5 text-xs rounded-lg cursor-pointer border transition-opacity hover:opacity-80"
              style={{ color: "var(--ui-primary)", "border-color": "var(--ui-primary)", "background-color": "transparent" }}
            >
              Regenerate
            </button>
          </div>

          <Show when={showJson()}>
            <pre class="rounded-lg border p-4 text-xs mb-4 overflow-auto max-h-[400px]"
              style={{ "background-color": "var(--ui-bg-subtle)", "border-color": "var(--ui-border)", color: "var(--ui-text-muted)", "font-family": "var(--ui-font-mono)" }}
            >
              {rawJson()}
            </pre>
          </Show>

          <Renderer node={spec()!} />
        </Show>

        <Show when={!spec() && !loading() && !error()}>
          <div class="py-16 text-center rounded-xl border border-dashed"
            style={{ "border-color": "var(--ui-border)", "background-color": "var(--ui-bg-subtle)" }}
          >
            <p class="text-sm mb-1" style={{ color: "var(--ui-text-muted)" }}>Click "Generate UI" to have an LLM create a dashboard from live health data.</p>
            <p class="text-xs" style={{ color: "var(--ui-text-placeholder)" }}>Each generation may produce a different layout.</p>
          </div>
        </Show>
      </div>
    </div>
  )
}
